global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: true
  inflation_radius: 10.0
  cost_scaling_factor: 5.0
  footprint_padding: 0.13

planner_patience: 1.5
controller_patience: 1.5
recovery_behavior_enabled: true