// Generated by gencpp from file vectornav/sync_in.msg
// DO NOT EDIT!


#ifndef VECTORNAV_MESSAGE_SYNC_IN_H
#define VECTORNAV_MESSAGE_SYNC_IN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vectornav
{
template <class ContainerAllocator>
struct sync_in_
{
  typedef sync_in_<ContainerAllocator> Type;

  sync_in_()
    : header()
    , gps_time(0.0)
    , sync_in_count(0)  {
    }
  sync_in_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_time(0.0)
    , sync_in_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _gps_time_type;
  _gps_time_type gps_time;

   typedef uint32_t _sync_in_count_type;
  _sync_in_count_type sync_in_count;




  typedef boost::shared_ptr< ::vectornav::sync_in_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vectornav::sync_in_<ContainerAllocator> const> ConstPtr;

}; // struct sync_in_

typedef ::vectornav::sync_in_<std::allocator<void> > sync_in;

typedef boost::shared_ptr< ::vectornav::sync_in > sync_inPtr;
typedef boost::shared_ptr< ::vectornav::sync_in const> sync_inConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vectornav::sync_in_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vectornav::sync_in_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vectornav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'vectornav': ['/home/capra/capra/src/vectornav/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vectornav::sync_in_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vectornav::sync_in_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vectornav::sync_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vectornav::sync_in_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vectornav::sync_in_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vectornav::sync_in_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vectornav::sync_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2086a0f9af37a9d42ba81363cb03ae33";
  }

  static const char* value(const ::vectornav::sync_in_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2086a0f9af37a9d4ULL;
  static const uint64_t static_value2 = 0x2ba81363cb03ae33ULL;
};

template<class ContainerAllocator>
struct DataType< ::vectornav::sync_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vectornav/sync_in";
  }

  static const char* value(const ::vectornav::sync_in_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vectornav::sync_in_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header       header\n\
float64		      gps_time\n\
uint32                sync_in_count\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vectornav::sync_in_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vectornav::sync_in_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_time);
      stream.next(m.sync_in_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct sync_in_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vectornav::sync_in_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vectornav::sync_in_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gps_time: ";
    Printer<double>::stream(s, indent + "  ", v.gps_time);
    s << indent << "sync_in_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sync_in_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VECTORNAV_MESSAGE_SYNC_IN_H
