global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 1.75
  publish_frequency: 1.0
  static_map: true

  # default 10.0
  inflation_radius: 20.0

  # default 5.0
  cost_scaling_factor: 4.0

  # default 1.4
  robot_radius: 1.1

  # default 0.1
  footprint_padding: 0.0
