global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true

  # default 10.0
  inflation_radius: 95.0

  # default 5.0
  cost_scaling_factor: 10.0

  # default 1.4
  robot_radius: 1.3

  # default 0.1
  footprint_padding: 0.2
