local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true

  # default 6.0
  width: 5.0

  # default 6.0
  height: 5.0

  resolution: 0.05

  # default 0.4
  inflation_radius: 0.5

  # default 3.0
  cost_scaling_factor: 12.2
